#!/usr/bin/env bash
# Displays information about domains

# Get domain information
get_subdomain_info() {
	local domain="$1"
	local subdomain="$2"
	local record_info
	record_info=$(dig +short "${subdomain}.${domain}")
	echo "The subdomain ${subdomain} is an A record and points to ${record_info}"
}

if [ -z "$1" ]; then
	echo "Usage: $0 domain [subdomain]"
	exit 1
fi

domain=$1
subdomain=$2

if [ -n "$subdomain" ]; then
	get_subdomain_info "$domain" "$subdomain"
else
	for sub in www lb-01 web-01 web-02; do
		get_subdomain_info "$domain" "$sub"
	done
fi
