#!/usr/bin/env bash
# Displays information about domains

# Get domain information
get_subdomain_info() {
	local domain="$1"
	local subdomain="$2"

	# Query DNS records for the requested subdomain
	local dns_info
	dns_info=$(dig "$subdomain.$domain" | awk '/ANSWER SECTION/ {getline; print}')

	# Return relevant details from DNS records
	local record_type
	record_type=$(echo "$dns_info" | awk '{print $4}')
	local destination
	destination=$(echo "$dns_info" | awk '{print $5}')

	# Print the required response
	echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

domain=$1
subdomain=$2

# If subdomain is not specified, return default subdomain information
if [ -z "$subdomain" ]; then
	get_subdomain_info "$domain" "www"
	get_subdomain_info "$domain" "lb-01"
	get_subdomain_info "$domain" "web-01"
	get_subdomain_info "$domain" "web-02"
else
	# Return the specified subdomain information
	get_subdomain_info "$domain" "$subdomain"
fi
