#!/usr/bin/env bash
# Script transfers a file from the client to the server

if [ "$#" -ne 4 ]; then
	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

FILE_PATH=$1
SERVER_IP=$2
USERNAME=$3
SSH_KEY=$4

scp -i "$SSH_KEY" -o StrictHostKeyChecking=no "$FILE_PATH" "$USERNAME@$SERVER_IP":~/

if [ $? -eq 0 ]; then
	echo "File transfer successful!"
else
	echo "File transfer failed."
fi
