#!/usr/bin/env bash
#Install nginx server

# Update the package list and install Nginx
apt-get update -y
apt-get install nginx -y

# Ensure that nginx is listening to port 80
sed -i 's/listen 80 default_server;/listen 80 default_server;/' /etc/nginx/sites-available/default
sed -i 's/listen \[::\]:80 default_server;/listen \[::\]:80 default_server;/' /etc/nginx/sites-available/default

# Create a HTML page for the homepage
echo "Hello World!" | sudo tee /var/www/html/index.html

# Restart Nginx
sudo service nginx restart
