#!/usr/bin/env bash
# This script configures Nginx so that its HTTP response contains a
# custom header

set -e

# Update packages and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Set up the hostname
HOSTNAME=$(hostname)

# Set up Nginx to include the custom header
CUSTOM_HEAD="server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	index index.html index.htm;

	server_name _;

	location / {
		add_header X-Served-By $HOSTNAME;
		try_files \$uri \$uri/ =404;
	}
}"
echo -e "$CUSTOM_HEAD" > /etc/nginx/sites-available/default

# Restart Nginx for changes to be applied
if command -v systemctl >/dev/null 2>&1; then
	sudo systemctl restart nginx
else
	sudo service nginx restart
fi
