#!/usr/bin/env bash
# Installs and configures HAproxy for load balancing


set -e

# Update packages and install HAproxy
sudo apt-get update
sudo apt-get install -y haproxy

# Set parameters for HAproxy
HA_PROXY="global
	log /dev/log local0
	log /dev/log local1 notice
	chroot /var/lib/haproxy
	stats socket /run/haproxy/admin.sock mode 660 level admin
	statstimeout 30s
	user haproxy
	group haproxy
	daemon

defaults
	log	global
	option	httplog
	option	dontlognull
	timeout	connect	5000ms
	timeout	client	5000ms
	timeout	server	5000ms
	errorfile	400	/etc/haproxy/errors/400.http
	errorfile	403	/etc/haproxy/errors/403.http
	errorfile	408	/etc/haproxy/errors/408.http
	errorfile	500	/etc/haproxy/errors/500.http
	errorfile	502	/etc/haproxy/errors/502.http
	errorfile	503	/etc/haproxy/errors/503.http
	errorfile	504	/etc/haproxy/errors/504.http

frontend http_front
	bind *:80
	default_backend http_back

backend http_back
	balance roundrobin
	server web-01 52.201.158.6:80 check
	server web-02 3.90.82.12:80 check
"

echo -e "$HA_PROXY" | sudo tee /etc/haproxy/haproxy.cfg > /dev/null

# Reboot HAproxy for changes to be applied
sudo systemctl restart haproxy
sudo systemctl enable haproxy

# Confirm that HAproxy is functional
sudo systemctl status haproxy
