#!/usr/bin/env bash
# Displays 'To infinity and beyond' indefinitely. In between each iteration of the loop, add a sleep 2. I am invincible!!! when receiving a SIGTERM signal

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
