#!/usr/bin/env bash
# Displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line

str_count=1
while [ $str_count -le 10 ]
do
	echo "Best School"
	if [ $str_count -eq 9 ]
	then
		echo "Hi"
	fi
	((str_count++))
done
