#!/usr/bin/env bash
# Loops from 1 to 10. 4 prints bad luck. 8 prints good luck. Else print Best School

str_count=1
while [ $str_count -le 10 ]
do
	if [ $str_count -eq 4 ]; then
		echo "bad luck"
	elif [ $str_count -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((str_count++))
done
