#!/usr/bin/env bash
# Displays the content of the current directory in a list format where only the part of the name after the first dash is displayed


my_list=$(ls)

for qz in $my_list;do
	echo "$qz" | cut -d '-' -f2
done
