#!/usr/bin/env bash
# This script configures an Ubuntu server
# localhost resolves to 127.0.0.2
# and Facebook to 8.8.8.8

cp /etc/hosts ~/hosts.bak

# Create a document with the necessary mappings
echo "127.0.0.2	localhost" > ~/hosts.new
echo "8.8.8.8	facebook.com" >> ~/hosts.new

# Copy the files to the pathway "/etc/hosts"
sudo cp -f ~/hosts.new /etc/hosts

# Remove any temporary files in the directory
rm ~/hosts.new
