#!/usr/bin/env bash
# Ensure that the container is running as Nginx user

sed -i 's/user  *root/user  nginx/' /etc/nginx/nginx.conf
sed -i 's/listen 80/listen 8080/' /etc/nginx/sites-available/default

chown -R nginx:nginx /var/log/nginx
chown -R nginx:nginx /var/cache/nginx

service nginx restart
